/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './app/**/*.{js,ts,jsx,tsx}',
    './src/**/*.{js,ts,jsx,tsx}'
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#0f172a",
        "on-tertiary-fixed-variant": "#1e40af",
        "on-error": "#ffffff",
        "error-container": "#fee2e2",
        "surface-dim": "#f8f8f6",
        "secondary-fixed-dim": "#99f6e4",
        "outline": "#cbd5e1",
        "secondary-container": "#ccfbf1",
        "on-tertiary-fixed": "#1e3a8a",
        "on-secondary-fixed": "#042f2e",
        "tertiary": "#3b82f6",
        "background": "#f8f8f6",
        "on-surface-variant": "#475569",
        "error": "#ef4444",
        "tertiary-fixed-dim": "#bfdbfe",
        "secondary": "#0d5a5e",
        "on-background": "#0f172a",
        "surface-container-high": "#e8e8e6",
        "surface": "#ffffff",
        "inverse-primary": "#fcd34d",
        "primary-fixed": "#fef3c7",
        "primary": "#ecb613",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#fde68a",
        "on-secondary-container": "#134e4a",
        "surface-container-highest": "#e2e2e0",
        "surface-bright": "#ffffff",
        "outline-variant": "#e2e8f0",
        "on-surface": "#0f172a",
        "primary-container": "#fef3c7",
        "secondary-fixed": "#ccfbf1",
        "on-primary-fixed": "#451a03",
        "surface-container": "#f1f1ef",
        "inverse-on-surface": "#f8fafc",
        "inverse-surface": "#1e293b",
        "on-secondary-fixed-variant": "#115e59",
        "tertiary-container": "#dbeafe",
        "surface-variant": "#f1f5f9",
        "on-primary-fixed-variant": "#78350f",
        "on-error-container": "#991b1b",
        "on-primary-container": "#92400e",
        "on-tertiary-container": "#1e40af",
        "tertiary-fixed": "#dbeafe",
        "surface-tint": "#ecb613",
        "surface-container-low": "#f8f8f6"
      },
      fontFamily: {
        'montserrat': ['Montserrat', 'sans-serif'],
        'playfair': ['Playfair Display', 'serif'],
        'inter': ['Inter', 'sans-serif'],
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      typography: (theme) => ({
        DEFAULT: {
          css: {
            maxWidth: '100%',
            color: 'inherit',
            lineHeight: '1.75',
            table: {
              width: '100%',
              borderCollapse: 'collapse',
              marginTop: '2em',
              marginBottom: '2em',
              overflowX: 'auto',
              display: 'block',
            },
            'thead th': {
              backgroundColor: theme('colors.blue.50'),
              color: theme('colors.blue.900'),
              fontWeight: '600',
              border: `1px solid ${theme('colors.blue.200')}`,
              padding: '0.75rem',
            },
            'tbody td': {
              border: `1px solid ${theme('colors.blue.200')}`,
              padding: '0.75rem',
            },
            'ul': {
              listStyleType: 'disc',
              paddingLeft: '1.5em',
            },
            'ul li::marker': {
              color: theme('colors.blue.600'),
            },
            'ol': {
              listStyleType: 'decimal',
              paddingLeft: '1.5em',
            },
            'ol li::marker': {
              color: theme('colors.blue.600'),
              fontWeight: '600',
            },
          },
        },
      }),
    },
  },
  plugins: [
    require('@tailwindcss/typography'),
  ],
};